Repository openshift/jenkins, pull requests merged in 2018-02, with the labels that each got.

#503 add imagestream+template files to repo
  openshift/imagestreams/jenkins-centos7.json
  openshift/imagestreams/jenkins-rhel7.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent.json
Labels: size/XL

#505 bump sync and client plugins for recent fixes
  2/contrib/openshift/base-plugins.txt
Labels: size/XS

#502 update plugins to Jenkins 2
  2/contrib/openshift/base-plugins.txt
Labels: size/M

#506 bump login, sync plugins for recent fixes
  2/contrib/openshift/base-plugins.txt
Labels: size/XS

#508 bump sync plugin for recent fix
  2/contrib/openshift/base-plugins.txt
Labels: size/XS

#510 update core/plugin versions for recent jenkins security advisories
  2/Dockerfile
  2/contrib/openshift/base-plugins.txt
Labels: size/S

#511 bump sync plugin for ssh secret validation fix
  2/contrib/openshift/base-plugins.txt
Labels: size/XS

#512 bump sync plugin for del bc fix
  2/contrib/openshift/base-plugins.txt
Labels: size/XS

#513 change version label to 3.9
  2/Dockerfile.rhel7
Labels: size/XS

#514 change version label to 3.7
  2/Dockerfile.rhel7
Labels: size/XS

#515 Fix relative links in README
  README.md
Labels: size/XS
