Repository openshift/jenkins, pull requests merged in 2018-07, with the labels that each got.

#635 remove dead link to java options
  2/contrib/s2i/run
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, lgtm, size/XS

#634 🔒 Upgrade plugins for Jenkins advisory 2018-06-25
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#636 bump container cap to 100
  2/contrib/jenkins/kube-slave-common.sh
Labels: approved, lgtm, size/XS

#639 bump container cap to 100 for jenkins 1 and 2
  2/contrib/jenkins/kube-slave-common.sh
Labels: approved, lgtm, size/XS

#646 similar to rhel, bypass on centos of rpm -V on java rpms
  2/Dockerfile
  slave-base/Dockerfile
  slave-maven/Dockerfile
Labels: approved, lgtm, size/S

#642 bump container cap to 100
  2/contrib/jenkins/kube-slave-common.sh
Labels: approved, lgtm, size/XS

#643 replace the term docker with container
  2/Dockerfile.rhel7
  agent-maven-3.5/Dockerfile.rhel7
  agent-nodejs-8/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile.rhel7
  slave-nodejs/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#644 bump container cap to 100 for jenkins 2
  2/contrib/jenkins/kube-slave-common.sh
Labels: approved, lgtm, size/XS

#649 Pick 624 3.8
  2/Dockerfile
  slave-base/Dockerfile
  slave-maven/Dockerfile
Labels: approved, lgtm, size/S

#650 Pick 624 3.6
  2/Dockerfile
  slave-base/Dockerfile
  slave-maven/Dockerfile
Labels: approved, lgtm, size/S

#654 replace the term docker with container
  2/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile.rhel7
  slave-nodejs/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#651 replace the term docker with container
  2/Dockerfile.rhel7
  agent-maven-3.5/Dockerfile.rhel7
  agent-nodejs-8/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile.rhel7
  slave-nodejs/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#652 replace the term docker with container
  2/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile.rhel7
  slave-nodejs/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#638 bump container cap to 100 for jenkins 1 and 2
  2/contrib/jenkins/kube-slave-common.sh
Labels: approved, lgtm, size/XS

#653 replace the term docker with container
  2/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile.rhel7
  slave-nodejs/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#655 replace the term docker with container
  2/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile.rhel7
  slave-nodejs/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#657 add lockable resource plugin for openshift client plugin
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#625 ⬆ Upgrade Jenkins to latest LTS 2.121.1
  2/Dockerfile
Labels: approved, lgtm, size/XS

#662 bump client, sync plugin versions for recent changes
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#664 ⬆ Upgrade Jenkins to latest LTS 2.121.2
  2/Dockerfile
Labels: approved, lgtm, size/XS

#663 add files for prow jenkins e2e job that allow tagging image to be tes…
  test-e2e/Dockerfile
  test-e2e/tag-in-image.sh
Labels: approved, lgtm, size/M

#665 switch to new rhel registry
  2/contrib/jenkins/kube-slave-common.sh
  openshift/imagestreams/jenkins-rhel7.json
Labels: approved, lgtm, size/XS

#667 switch to new registry
  openshift/imagestreams/jenkins-rhel7.json
Labels: approved, lgtm, size/XS

#669 bump sync plugin
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS
