Repository openshift/jenkins, pull requests merged in 2018-05, with the labels that each got.

#593 Upgrade to latest LTS 2.107.3
  2/Dockerfile
Labels: approved, lgtm, size/XS

#592 default jenkins master, jnlp tunnel, to no_proxy list
  README.md
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, lgtm, size/S

#597 remove unnecessary tick marks
  README.md
Labels: approved, lgtm, size/XS

#599 Fix the value of -Djavamelody.displayed-counters
  2/contrib/s2i/run
Labels: approved, lgtm, size/XS

#588 do not enable i686 unless we are x86_64 based
  2/Dockerfile
  2/Dockerfile.rhel7
  2/contrib/s2i/run
  agent-maven-3.5/Dockerfile
  agent-maven-3.5/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
  slave-base/contrib/bin/run-jnlp-client
  slave-maven/Dockerfile
  slave-maven/Dockerfile.rhel7
Labels: approved, lgtm, size/M

#600 don't configure javac in base slave image
  agent-maven-3.5/contrib/bin/configure-agent
  slave-base/contrib/bin/run-jnlp-client
  slave-maven/contrib/bin/configure-slave
Labels: approved, lgtm, size/M

#604 quick typo fix and formatting fix
  README.md
Labels: approved, lgtm, size/XS

#607 default jenkins master, jnlp tunnel, to no_proxy list
  README.md
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, lgtm, size/S

#608 default jenkins master, jnlp tunnel, to no_proxy list
  README.md
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, lgtm, size/S

#609 default jenkins master, jnlp tunnel, to no_proxy list
  README.md
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, lgtm, size/S

#611 add NPM_MIRROR_URL support to use a node mirror registry
  agent-nodejs-8/README.md
  agent-nodejs-8/contrib/bin/configure-agent
Labels: approved, lgtm, size/S

#610 Add save-artifacts s2i script for incremental builds
  2/contrib/jenkins/install-plugins.sh
  2/contrib/s2i/assemble
  2/contrib/s2i/save-artifacts
Labels: approved, lgtm, size/S

#615 bump sync plugin for fabric bug pickup, 3.11 feature for updating fab…
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#616 Switch master branch to v3.11
  2/Dockerfile
  2/Dockerfile.rhel7
  2/release.version
  agent-maven-3.5/Dockerfile.rhel7
  openshift/imagestreams/jenkins-centos7.json
  openshift/imagestreams/jenkins-rhel7.json
Labels: approved, lgtm, size/S

#612 add -XX:ErrorFile as option
  2/contrib/s2i/run
  README.md
  openshift/templates/jenkins-persistent.json
Labels: approved, lgtm, size/S

#614 Amend arguments if none passed to run-jnlp-client
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, lgtm, size/S

#586 bump k8s plugin to pick up our config via yaml change to the console
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#622 pull in fix for https://issues.jenkins-ci.org/browse/JENKINS-47112 an…
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS
