Repository openshift/jenkins, pull requests merged in 2018-12, with the labels that each got.

#746 adjust jenkins e2e img env var name to new convention
  test-e2e/Dockerfile
  test-e2e/tag-in-image.sh
Labels: approved, lgtm, size/S

#749 bump lts for https://jenkins.io/security/advisory/2018-12-05/ and htt…
  2/Dockerfile
  2/contrib/s2i/run
  test-e2e/Dockerfile
  test-e2e/tag-in-image.sh
Labels: approved, lgtm, size/S

#750 fix spacing / make sure new lts worked
  2/contrib/s2i/run
Labels: approved, lgtm, size/XS

#753 update README for manual oc install instructions
  README.md
Labels: approved, lgtm, size/XS

#744 ⬆ Upgrade Jenkins to latest LTS 2.138.4
  2/Dockerfile
  2/contrib/s2i/run
Labels: approved, lgtm, size/S

#754 add back in rpm -V for java rpms since now on 7.6 rhel
  2/Dockerfile
  2/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile
  slave-maven/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#755 add back in rpm -V for java rpms since now on 7.6 rhel; don't try to …
  2/Dockerfile
  2/Dockerfile.rhel7
  agent-maven-3.5/Dockerfile
  agent-maven-3.5/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#758 add back in rpm -V for java rpms since now on 7.6 rhel; don't try to …
  2/Dockerfile
  2/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile
  slave-maven/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#757 Rpm v stutter 310
  2/Dockerfile
  2/Dockerfile.rhel7
  agent-maven-3.5/Dockerfile
  agent-maven-3.5/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile
  slave-maven/Dockerfile.rhel7
Labels: approved, lgtm, size/M

#756 add rpm -V back in for agent-maven as well
  agent-maven-3.5/Dockerfile
  agent-maven-3.5/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#759 [3.8] add back in rpm -V for java rpms since now on 7.6 rhel; don't try to …
  2/Dockerfile
  2/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile
  slave-maven/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#760 [3.7] add back in rpm -V for java rpms since now on 7.6 rhel; don't try to …
  2/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#761 add back in rpm -V for java rpms since now on 7.6 rhel; don't try to …
  2/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#763 fix docker spec for rhel imagestream 2 tag
  openshift/imagestreams/jenkins-rhel7.json
Labels: approved, lgtm, size/XS

#765 bump client plugin for 2-container agent fix
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm
