Repository openshift/jenkins, pull requests merged in 2018-09, with the labels that each got.

#687 make version env var less specific so it doesn't get outdated
  2/Dockerfile.rhel7
Labels: size/XS

#690 bump to v4.0
  2/Dockerfile
  2/Dockerfile.rhel7
  2/release.version
  openshift/imagestreams/jenkins-centos7.json
  openshift/imagestreams/jenkins-rhel7.json
Labels: approved, lgtm, size/S

#692 bump sync for more secret/credential mapping permutations
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#694 disable various override paths based on the associated env vars == false
  2/contrib/s2i/run
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, lgtm, size/S

#697 bump client plugin for vfreex launch oc improvement
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#704 URL of OKD is docs.okd.io now
  README.md
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent.json
Labels: approved, lgtm, size/XS

#705 Create ppc64le jenkins supported imagestream
  openshift/imagestreams/jenkins-rhel7-ppc64le.json
Labels: approved, lgtm, size/M

#707 bump sync, client plugins for fixes to recent bugs reported upstream
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS
