Repository openshift/jenkins, pull requests merged in 2018-03, with the labels that each got.

#517 pull in recent login plugin fixes
  2/contrib/openshift/base-plugins.txt
Labels: size/XS

#518 pull in recent login plugin fixes
  2/contrib/openshift/base-plugins.txt
Labels: size/XS

#516 Fix migration rhel
  2/Dockerfile
  2/Dockerfile.rhel7
  2/contrib/s2i/run
  README.md
Labels: size/M

#521 formatting and longer test timeout
  2/contrib/s2i/run
  hack/build.sh
Labels: size/L

#525 use alternatives command on javac as well for maven
  2/contrib/s2i/run
  slave-base/contrib/bin/run-jnlp-client
Labels: size/XS

#440 perform update center syncrhonization during startup instead of first login
  2/contrib/openshift/configuration/init.groovy.d/init.groovy
  pkg/jenkins/jenkins.go
Labels: size/XS

#527 port recent origin template changes around less aggressive timeouts
  2/test/jenkins_test.go
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent.json
Labels: size/S

#530 revert our introduction of init.groovy while we sort out image extend…
  2/contrib/openshift/configuration/init.groovy.d/init.groovy
Labels: size/XS

#531 revert our introduction of init.groovy while we sort out image extend…
  2/contrib/openshift/configuration/init.groovy.d/init.groovy
Labels: size/XS

#532 switch master branch to v3.10
  2/Dockerfile
  2/Dockerfile.rhel7
  2/release.version
Labels: size/XS

#534 add docker related debug around s2i test
  2/test/jenkins_test.go
  pkg/docker/docker.go
Labels: size/M

#538 match route timeout template updates in origin
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent.json
Labels: approved, lgtm, size/XS

#537 New agents
  Makefile
  README.md
  agent-maven-3.5/Dockerfile
  agent-maven-3.5/Dockerfile.rhel7
  agent-maven-3.5/README.md
  agent-maven-3.5/cccp.yml
  agent-maven-3.5/contrib/bin/configure-agent
  agent-maven-3.5/contrib/bin/scl_enable
  agent-maven-3.5/contrib/init.gradle
  agent-maven-3.5/contrib/settings.xml
  agent-maven-3.5/test/agent_maven_test.go
  agent-nodejs-8/Dockerfile
  agent-nodejs-8/Dockerfile.rhel7
  agent-nodejs-8/cccp.yml
  agent-nodejs-8/contrib/bin/scl_enable
  agent-nodejs-8/test/agent_nodejs_test.go
  hack/build.sh
  slave-base/contrib/bin/configure-agent
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, lgtm, size/XL

#539 update k8s plugin default pod templates to use new agent images
  2/contrib/jenkins/kube-slave-common.sh
  2/contrib/s2i/run
Labels: approved, lgtm, size/S

#541 bump sync plugin for https://trello.com/c/FxtSMIUm/1447-3-removing-a-…
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#542 bump jenkins to 3.10
  openshift/imagestreams/jenkins-centos7.json
  openshift/imagestreams/jenkins-rhel7.json
Labels: approved, lgtm, size/XS

#543 bump client plugin for multi-namespace, cluster config via groovy cha…
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#523 Migration fix 3.6
  2/Dockerfile
  2/Dockerfile.rhel7
  2/contrib/s2i/run
  README.md
Labels: approved, lgtm, size/L

#524 Migration fix 3.7
  2/Dockerfile
  2/Dockerfile.rhel7
  2/contrib/s2i/run
  README.md
Labels: approved, lgtm, size/M

#544 incur jenkins update center pain during startup vs. login via groovy …
  2/Dockerfile
  2/Dockerfile.rhel7
  2/contrib/openshift/configuration/init.groovy.d/update-center-init.groovy
Labels: approved, lgtm, size/XS

#546 bump to lts 2.107.1 announced this week
  2/Dockerfile
Labels: approved, lgtm, size/XS

#547 revert lts bump until we sort out login plugin serialization
  2/Dockerfile
Labels: approved, lgtm, size/XS

#536 Trivial wording fix
  1/contrib/s2i/assemble
  2/contrib/s2i/assemble
Labels: approved, lgtm, size/XS

#550 use local ref policy in imagestreams
  openshift/imagestreams/jenkins-centos7.json
  openshift/imagestreams/jenkins-rhel7.json
Labels: approved, lgtm, size/S

#552 move update center init groovy to background thread
  2/contrib/openshift/configuration/init.groovy.d/update-center-init.groovy
Labels: approved, lgtm, size/S

#551 allow for the disabling of memory intensive admin monitors via env va…
  2/contrib/openshift/configuration/config.xml.tpl
  2/contrib/s2i/run
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent.json
Labels: approved, lgtm, size/M

#553 bump sync plugin for watch logging and passive reconnect
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#555 add verification for KUBE_CA contents
  2/Dockerfile
  2/Dockerfile.rhel7
  2/contrib/jenkins/kube-slave-common.sh
  2/contrib/s2i/run
Labels: approved, lgtm, size/S

#556 use openssl to strip bag attributes as well
  2/contrib/jenkins/kube-slave-common.sh
Labels: approved, lgtm, size/XS

#548 go back to v2.107; bump login plugin to v1.0.7 to tolerate v2.107
  2/Dockerfile
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#559 change /etc/passwd chmod to 664
  2/Dockerfile
  2/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#560 add bzip2 to the images
  2/Dockerfile
  2/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#561 remove all v1 related content
  1/Dockerfile
  1/Dockerfile.rhel7
  1/README.md
  1/cccp.yml
  1/contrib/jenkins/fix-permissions
  1/contrib/jenkins/jenkins-common.sh
  1/contrib/jenkins/kube-slave-common.sh
  1/contrib/jenkins/plugins.sh
  1/contrib/openshift/base-plugins.txt
  1/contrib/openshift/configuration/config.xml.tpl
  1/contrib/openshift/configuration/credentials.xml.tpl
  1/contrib/openshift/configuration/jobs/OpenShift Sample/config.xml
  1/contrib/openshift/configuration/org.jenkinsci.main.modules.sshd.SSHD.xml
  1/contrib/openshift/configuration/users/admin/config.xml
  1/contrib/openshift/password-encoder.jar
  1/contrib/s2i/assemble
  1/contrib/s2i/run
  1/test/jenkins_test.go
  1/test/testdata/s2i/configuration/config.xml
  1/test/testdata/s2i/configuration/jobs/sample-app-test/config.xml
  1/test/testdata/s2i/configuration/jobs/sample-app-test/promotions/Verified/config.xml
  1/test/testdata/s2i/plugins.txt
  1/test/testdata/s2i/plugins/sample.jpi.pinned
  1/test/testdata/testjob.xml
  Makefile
  README.md
Labels: approved, lgtm, size/XXL

#562 fix some slave/agent conversion misses for rhel7
  agent-maven-3.5/Dockerfile.rhel7
  agent-nodejs-8/Dockerfile.rhel7
Labels: approved, lgtm, size/S
