Repository openshift/jenkins, pull requests merged in 2018-10, with the labels that each got.

#706 Upgrade to job-dsl 1.70
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#711 Fix bash syntax errors
  2/contrib/s2i/run
Labels: approved, lgtm, size/S

#715 Dockerfile edits and set java path for multiarch builds
  2/Dockerfile.rhel7
  2/contrib/s2i/run
  agent-maven-3.5/Dockerfile.rhel7
  slave-base/contrib/bin/run-jnlp-client
  slave-maven/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#719 various new launcher related fixes; add verifyService to client plugin
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#725 remove v3.10 deprecated maven/nodejs images
  2/contrib/s2i/run
  Makefile
  README.md
  slave-maven/Dockerfile
  slave-maven/Dockerfile.rhel7
  slave-maven/README.md
  slave-maven/cccp.yml
  slave-maven/contrib/bin/configure-slave
  slave-maven/contrib/bin/scl_enable
  slave-maven/contrib/init.gradle
  slave-maven/contrib/settings.xml
  slave-maven/test/slave_maven_test.go
  slave-nodejs/Dockerfile
  slave-nodejs/Dockerfile.rhel7
  slave-nodejs/cccp.yml
  slave-nodejs/contrib/bin/scl_enable
  slave-nodejs/test/slave_nodejs_test.go
Labels: approved, lgtm, size/XL

#724 remove old plugin based sample and plugin itself
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/configuration/jobs/OpenShift Sample/config.xml
  README.md
Labels: approved, lgtm, size/M

#726 bump client plugin for thread leak fix
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#712 create container.yaml for odcs multi-arch builds
  2/container.yml
Labels: approved, lgtm, size/XS
