Repository openshift/jenkins, pull requests merged in 2018-04, with the labels that each got.

#565 switch from mv to rsync in assemble script to better account for exis…
  2/contrib/s2i/assemble
Labels: approved, lgtm, size/XS

#566 bump login/client/sync for recent fixes
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#572 bump client/sync plugins for recent changes
  2/Dockerfile.rhel7
  2/contrib/openshift/base-plugins.txt
  agent-maven-3.5/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#573 Upgrade Jenkins to 2.107.2; mailer plugin to 1.21
  2/Dockerfile
  2/contrib/openshift/base-plugins.txt
  README.md
Labels: approved, lgtm, size/M

#571 Add support for NPM modules with native extensions
  agent-nodejs-8/Dockerfile
  agent-nodejs-8/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#577 ⬆ Upgrade htmlpublisher to 1.16 for security issue
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#579 temp remove of rpm -V until origin int rhel 7.5 repos picks up fedora…
  2/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#578 temp remove of rpm -V until origin int rhel 7.5 repos picks up fedora…
  2/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
  slave-maven/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#581 more sync/client plugin 3.10 fixes
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm

#583 bump client/sync plugins for recent fixes
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#585 head off monitor plugin interference (via filter induced session crea…
  2/contrib/s2i/run
Labels: approved, lgtm, size/XS

#587 bump sync plugin for recent changes
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#590 bump sync plugin for upd on prompt, only poll build status once
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS
