Repository openshift/jenkins, pull requests merged in 2019-09, with the labels that each got.

#917 Bug 1747303: Bump jenkins to version 2.176.3
  2/Dockerfile
  2/Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#915 Bug 1747302: Bump Jenkins to 2.176.3
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#922 Bug 1743279: Bump plugins versions
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#925 Added label stating Jenkins Version
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#914 Adding first empty changelog
  CHANGELOG.md
Labels: approved, lgtm, size/S

#928 Bump openshift-jenkins-login-plugin to version 1.0.20
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/S

#929 Bump openshift-jenkins-login-plugin to 1.0.20
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/S

#899 Prometheus Monitoring Integration
  2/contrib/openshift/base-plugins.txt
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-persistent-monitored.json
Labels: approved, lgtm, size/XL

#932 Added MAVEN_MIRROR_URL description to env vars in README.md
  README.md
Labels: approved, lgtm, size/XS

#933 Bug 1754968: Revert set alternatives to java 1.8.0
  2/Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
