Repository openshift/jenkins, pull requests merged in 2019-01, with the labels that each got.

#767 🔒 Upgrade plugin versions for security-1266
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#776 Add agent imagestreams
  openshift/imagestreams/jenkins-agent-maven-centos7.json
  openshift/imagestreams/jenkins-agent-maven-rhel7.json
  openshift/imagestreams/jenkins-agent-nodejs-centos7.json
  openshift/imagestreams/jenkins-agent-nodejs-rhel7.json
Labels: approved, lgtm, size/L

#779 bump login plugin to move off of /oapi endpoints
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#780 🔒 Upgrade plugin versions for security-1266
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#781 bump login plugin for correct api version for self-sar on 4.0
  2/contrib/openshift/base-plugins.txt
Labels: approved, size/XS
