Repository openshift/jenkins, pull requests merged in 2019-07, with the labels that each got.

#881 disable gradle test (gradle is okd/centos only) for ci.openshift push…
  agent-maven-3.5/test/agent_maven_test.go
Labels: approved, lgtm, size/XS

#882 disable gradle test (gradle is okd/centos only) for ci.openshift push…
  slave-maven/test/slave_maven_test.go
Labels: approved, lgtm, size/XS

#883 disable gradle test (gradle is okd/centos only) for ci.openshift push…
  slave-maven/test/slave_maven_test.go
Labels: approved, lgtm, size/XS

#884 disable gradle test (gradle is okd/centos only) for ci.openshift push…
  agent-maven-3.5/test/agent_maven_test.go
Labels: approved, lgtm, size/XS

#885 Bump jenkins-sync-plugin version to 1.0.39
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#886 add devtools to owners
  OWNERS
Labels: approved, lgtm, size/XS

#887 Bug 1731034: Bump jenkins version to 2.176.2
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#888 Bug 1731024: Bumpin Jenkins version in centos image
  2/Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#891 add devtools to 3.11 owners file
  OWNERS
Labels: approved, lgtm, size/XS

#890 Bug 1731068: Update Jenkins Devtools Owners
  OWNERS
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#898 Bug NEED CLONE 1732346: Bump Credentials Binding Plugin to v1.19
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#896 remove all yum-config-manager invocations from Dockerfiles
  2/Dockerfile.rhel7
  agent-maven-3.5/Dockerfile.rhel7
  agent-nodejs-8/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#895 change maintainer in dockerfiles to Akram
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/Dockerfile.rhel7
  agent-nodejs-8/Dockerfile.localdev
  agent-nodejs-8/Dockerfile.rhel7
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/S
