Repository openshift/jenkins, pull requests merged in 2019-02, with the labels that each got.

#772 update Jenkins to 2.150.2 LTS
  2/Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#784 remove tags for jenkins-1-*
  openshift/imagestreams/jenkins-centos7.json
  openshift/imagestreams/jenkins-rhel7.json
Labels: approved, lgtm, size/M

#788 [3.11] bump login to 1.0.15 for 2.150.2 fix
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#789 bump login for oauth provider endpoint change
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#790 readme changes for 4.0, jenkins sec advisories; update agent Dockerfi…
  README.md
  agent-maven-3.5/Dockerfile
  agent-nodejs-8/Dockerfile
Labels: approved, lgtm, size/M

#774 sync up the base image names and use cli base image explicitly
  2/Dockerfile
  2/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#791 🔒 Upgrade plugins for Jenkins security advisory 2019-01-28
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#792 🔒 Upgrade plugins for Jenkins security advisory 2019-01-28
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#794 bump sync plugin for new credential type added by upstream contributor
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#797 Fix issue #795 in 3.11
  agent-nodejs-8/Dockerfile
  agent-nodejs-8/Dockerfile.rhel7
Labels: approved, lgtm, ok-to-test, size/XS

#796 Fix issue #795
  agent-nodejs-8/Dockerfile
  agent-nodejs-8/Dockerfile.rhel7
Labels: approved, lgtm, ok-to-test, size/XS

#798 set default memory limit to 1gig in jenkins template
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent.json
Labels: approved, lgtm, size/XS

#800 bump client plugin for more agent launcher fixes
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#801 Take responsibility for creating the /var/lib/origin dir
  2/Dockerfile
  2/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#803 add utility for getting the complete plugin list from base-plugins.txt
  plugin-lister/Dockerfile-plugin-lister
  plugin-lister/lister.sh
Labels: approved, lgtm, size/XS

#804 bump client plugin for slow oc find fix
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#805 explicitly cite 3.11 in FROM clauses
  2/Dockerfile
  2/Dockerfile.rhel7
  agent-maven-3.5/Dockerfile
  agent-maven-3.5/Dockerfile.rhel7
  agent-nodejs-8/Dockerfile
  agent-nodejs-8/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#806 recover from jenkins deps backleveling workflow-durable-task-step fro…
  2/contrib/openshift/base-plugins.txt
  plugin-lister/Dockerfile-plugin-lister
Labels: approved, lgtm, size/XS
