Repository openshift/jenkins, pull requests merged in 2019-08, with the labels that each got.

#901 Bug 1729522: Bump openshift-sync-plugin to v1.0.40
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#905 Bug 1735527: Cve 2019 10356 bump jenkins plugin script security to 1.62
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#904 Bug 1735527: 3.11 cve 2019 10357 bump workflow cps global lib version to 2.15
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#903 Bug 1735528: cve-2019-10357: Bump-workflow-cps-global-lib-version-to-2.15
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#906 Bug 1735528: cve-2019-10356-bump-jenkins-plugin-script-security-to-1.62
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#908 Bump plugin versions wrt workflow-cps fix in client plugin
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#911 Bump openshift-sync version to 1.0.41
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#913 Bug 1735141: 3.11 bump jenkins sync plugin to 1.41
  2/Dockerfile
  2/Dockerfile.rhel7
  2/contrib/openshift/base-plugins.txt
  2/contrib/s2i/run
Labels: approved, bugzilla/valid-bug, lgtm, size/S
