Repository openshift/jenkins, pull requests merged in 2019-03, with the labels that each got.

#807 BUG 1679937: bump client plugin: update freestyle argument help for t…
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#808 🔒 Upgrade plugins for Jenkins advisory 2018-09-25
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#810 restructure jenkins core/plugin installs along api.ci vs. osbs/brew l…
  2/Dockerfile
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, lgtm, size/M

#812 remove 32 bit JVM
  2/Dockerfile
  2/Dockerfile.rhel7
  2/contrib/s2i/run
  README.md
  agent-maven-3.5/Dockerfile
  agent-maven-3.5/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, lgtm, size/M

#814 Dockerfile.rhel7 cleanup for hybrid core/plugin install behavior on a…
  2/Dockerfile
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, lgtm, size/M

#813 Upgrade plugins
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#815 🔒 Upgrade plugins for Jenkins security advisory 2019-03-06
  2/Dockerfile
  2/Dockerfile.rhel7
  2/contrib/openshift/base-plugins.txt
  agent-maven-3.5/Dockerfile
  agent-maven-3.5/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#818 remove yum install of openshift CLI (picked up from base image)
  2/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#816 Plugin bumps
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#819 get Dockerfile working for local buliding; more updates to README for v4
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  README.md
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/Dockerfile.rhel7
  agent-nodejs-8/Dockerfile
  agent-nodejs-8/Dockerfile.localdev
  agent-nodejs-8/Dockerfile.rhel7
  hack/build.sh
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/L

#822 bump client plugin for 1) process launch change to bypass flaky jenki…
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#817 Add adambkaplan as approver
  OWNERS
Labels: approved, lgtm, size/XS

#827 adjust agent config based on cluster version; augment readme around r…
  2/contrib/jenkins/kube-slave-common.sh
  README.md
Labels: approved, lgtm, size/M

#826 🔒 Upgrade plugins for Jenkins security advisory 2019-03-25
  2/Dockerfile.localdev
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#829 🔒 Upgrade plugins for Jenkins security advisory 2019-03-25
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#830 some more '--setopt=protected_multilib=false ' now needed for the pus…
  slave-maven/Dockerfile
Labels: approved, lgtm, size/XS

#828 fixes around tbr, 3.11 sec advisories, agent default img
  README.md
Labels: approved, lgtm, size/S
