Repository openshift/jenkins, pull requests merged in 2019-04, with the labels that each got.

#831 update contribution manifesto for 4.x convergence onto api.ci prow
  CONTRIBUTING_TO_OPENSHIFT_JENKINS_IMAGE_AND_PLUGINS.md
  CONTRIBUTING_TO_OPENSHIFT_PLUGINS.md
  README.md
Labels: approved, lgtm, size/XL

#832 minor fixes to recently published contrib guide
  CONTRIBUTING_TO_OPENSHIFT_JENKINS_IMAGE_AND_PLUGINS.md
Labels: approved, lgtm, size/M

#834 run yum update to avoid package mismatch between archs
  2/Dockerfile
  2/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, ok-to-test, size/XS

#838 bump jenkins core to 2.164.2 for Apr 10 2019 sec adv
  2/Dockerfile
Labels: approved, lgtm, size/XS

#833 🔒 Upgrade to latest LTS 2.164.2
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, lgtm, size/XS

#839 move from awk to grep for 3.11 slave image use tbr check (awk diff on…
  2/contrib/jenkins/kube-slave-common.sh
Labels: approved, lgtm, size/XS

#841 remove outdated comment
  slave-base/Dockerfile.localdev
Labels: approved, lgtm, ok-to-test, size/XS

#840 remove trailing whitespaces
  2/contrib/openshift/configuration/jenkins.CLI.xml
Labels: approved, lgtm, ok-to-test, size/XS

#842 bump client plugin for space in name fix
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS
