Repository openshift/jenkins, pull requests merged in 2019-11, with the labels that each got.

#971 Forcibely set JENKINS_URL and reflects JENKINS_SERVICE_NAME
  2/contrib/openshift/configuration/jenkins.model.JenkinsLocationConfiguration.xml.tpl
  2/contrib/s2i/run
Labels: approved, lgtm, size/S

#973 Bug 1764460: Re-ordering some plugins in alphabetical order
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#966 Format logs
  2/contrib/openshift/configuration/logging.properties
  2/contrib/s2i/run
Labels: approved, lgtm, size/XS

#974 Bug 1764462: cve-2019-10432: Stored xss vulnerability
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#982 Bug 1764466: 4.1 bz 1764466 cve 2019 10431
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#981 Bug 1764461: cve-2019-10432: Stored xss vulnerability
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#983 Bug 1771337: Bump openshfit-login-plugin to 1.0.21
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#987 Bug 1776760: Fix proxy with kubernetes.default
  2/contrib/s2i/run
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
