Repository openshift/jenkins, pull requests merged in 2019-10, with the labels that each got.

#936 Add Nodejs 10 Agent
  agent-nodejs-10/Dockerfile.localdev
  agent-nodejs-10/Dockerfile.rhel7
  agent-nodejs-10/README.md
  agent-nodejs-10/cccp.yml
  agent-nodejs-10/contrib/bin/configure-agent
  agent-nodejs-10/contrib/bin/scl_enable
  agent-nodejs-10/test/agent_nodejs_test.go
Labels: approved, lgtm, size/L

#935 Update slave-base to use jdk11
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
  slave-base/README.md
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, lgtm, size/M

#941 Remove gradle
  .gitignore
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/contrib/init.gradle
Labels: approved, lgtm, size/M

#943 Remove unused variable
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#945 Fix yum clean by deleting /var/cache/yum/x86_64/7Server/
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, lgtm, size/S

#946 Allow use of podman or buildah by using the BUILD_COMMAND variable
  README.md
  hack/build.sh
Labels: approved, lgtm, size/S

#942 Fix nodejs-10 images: missing space in sources
  agent-nodejs-10/Dockerfile.localdev
  agent-nodejs-10/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#944 Disable yum plugin subscription-manager
  2/Dockerfile.localdev
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  agent-nodejs-10/Dockerfile.localdev
  agent-nodejs-10/Dockerfile.rhel7
  agent-nodejs-8/Dockerfile.localdev
  agent-nodejs-8/Dockerfile.rhel7
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#947 Remove all uses of dumb-init
  .gitignore
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  Makefile
  agent-maven-3.5/Dockerfile.localdev
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/M

#948 Upgrade maven agent to openjdk-11
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#949 Manage proxy configuration for the maven agent
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/Dockerfile.rhel7
  agent-maven-3.5/contrib/bin/configure-agent
Labels: approved, lgtm, size/M

#950 Add ability to set proxy from env var for nodejs agent
  agent-nodejs-10/contrib/bin/configure-agent
Labels: approved, lgtm, size/M

#951 Adds proxy support for Jenkins master
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/s2i/run
  README.md
Labels: approved, lgtm, size/M

#952 Install jq on slave base image only
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/Dockerfile.rhel7
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/S

#953 Embed go-init to allow multistage build in AOS/Brew
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/go-init/Dockerfile
  2/go-init/LICENSE
  2/go-init/README.md
  2/go-init/main.go
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
  slave-base/go-init/Dockerfile
  slave-base/go-init/LICENSE
  slave-base/go-init/README.md
  slave-base/go-init/main.go
Labels: approved, lgtm, size/XL

#955 Fix: no_proxy was already handled
  2/contrib/s2i/run
Labels: approved, lgtm, size/XS

#956 Bump kubernetes plugin to 1.18.2 to support proxies on OpenJDK 11
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/S

#957 Allows proxy tunnelling for OpenJDK11
  2/contrib/s2i/run
Labels: approved, lgtm, size/XS

#959 because of this typo the NPM_MIRROR_URL was not working
  agent-nodejs-10/contrib/bin/configure-agent
Labels: approved, lgtm, ok-to-test, size/XS

#961 Set env LC_ALL and LANG to en_US.UTF-8 in slave images
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/Dockerfile.rhel7
  agent-nodejs-10/Dockerfile.localdev
  agent-nodejs-10/Dockerfile.rhel7
  agent-nodejs-8/Dockerfile.localdev
  agent-nodejs-8/Dockerfile.rhel7
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, size/M

#964 Bug 1764464: cve-2019-10432: Stored xss vulnerability
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#965 Add the team as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#968 Bug 1755812: Bump Sync Plugin to 1.0.42
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#967 Bug 1764481: Bump jenkins version to 2.176.4 : cve-2019-10401..10406
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
