Repository openshift/jenkins, pull requests merged in 2019-06, with the labels that each got.

#864 Bug 1716799: update requisite plugins for May31-2019 jenkins security…
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#863 Bug 1716798: update requisite plugins for May31-2019 jenkins security…
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#866 Allow plugin download to use an insecure repository
  2/contrib/jenkins/install-plugins.sh
  README.md
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent.json
Labels: approved, lgtm, size/M

#867 bump login/sync plugin versions for pom repository URL fix
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#868 Bug 1719477: bump openshift/jenkins plugin versions for pom repositor…
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#872 Jun112019 jenkins security advisory
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm, size/XS

#870 Bug 1720032: Jun112019 jenkins security advisory
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#873 readme updates for startup on PVs warning, extending the image with g…
  README.md
Labels: approved, lgtm, size/M

#871 Bug 1720033: Jun112019 jenkins security advisory
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#860 Bug 1714057: update requisite plugins for May21-2019 jenkins security…
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#874 update ART/OSBS instructions in contributing guide based on recent ch…
  CONTRIBUTING_TO_OPENSHIFT_JENKINS_IMAGE_AND_PLUGINS.md
Labels: approved, lgtm, size/XS

#876 fix up some 4.x text around tags; add quick brief on the 4.x image pa…
  README.md
Labels: approved, lgtm, size/S

#865 Bug 1717033: update requisite plugins for May31-2019 jenkins security…
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#869 Bug 1719795: bump login/sync plugin versions for pom repository URL fix
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#879 fix markdown syntax for bullet lists
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#878 various clean up to get 'make test' functional again for PR testing
  2/contrib/s2i/run
  2/test/jenkins_test.go
  agent-maven-3.5/test/agent_maven_test.go
  slave-base/Dockerfile.localdev
Labels: approved, lgtm, size/M

#793 use non-alpha version of oc cli on 3.11 slave-base
  2/Dockerfile
  2/Dockerfile.rhel7
  slave-base/Dockerfile
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm, ok-to-test, size/S
