Repository openshift/jenkins, pull requests merged in 2020-08, with the labels that each got.

#1125 Bump matrix plugin
  2/Dockerfile.localdev
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm

#1101 Update Dockerfile.localdev
  agent-nodejs-8/Dockerfile.localdev
Labels: approved, lgtm, ok-to-test

#1127 [release-4.5] Bug 1857559: Bump matrix plugin
  2/Dockerfile.localdev
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1132 [openshift-3.11] Bug 1857552: bump jenkins version to 2.235.1
  2/Dockerfile
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1135 Bug 1848611: Remove execution of rpm -e java-1.8.0.
  agent-maven-3.5/Dockerfile.rhel7
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1134 Bug 1868069: Fix missing proxy.yaml
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1137 [openshift-3.11] Bug 1850528: Login plugin 1.0.24: incorrect detection of openshift 3
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1126 [openshift-3.11] Bug 1857556: Bump matrix plugin
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1136 [head] Update and rename imagestreams files
  openshift/imagestreams/jenkins-agent-base-rhel.yaml
  openshift/imagestreams/jenkins-agent-maven-centos.json
  openshift/imagestreams/jenkins-agent-maven-centos.yaml
  openshift/imagestreams/jenkins-agent-maven-rhel.json
  openshift/imagestreams/jenkins-agent-maven-rhel.yaml
  openshift/imagestreams/jenkins-agent-nodejs-centos.json
  openshift/imagestreams/jenkins-agent-nodejs-centos.yaml
  openshift/imagestreams/jenkins-agent-nodejs-rhel.json
  openshift/imagestreams/jenkins-agent-nodejs-rhel.yaml
  openshift/imagestreams/jenkins-centos.json
  openshift/imagestreams/jenkins-centos.yaml
  openshift/imagestreams/jenkins-centos7.yaml
  openshift/imagestreams/jenkins-rhel.json
  openshift/imagestreams/jenkins-rhel.yaml
  openshift/imagestreams/jenkins-rhel7-ppc64le.json
Labels: approved, lgtm

#1107 [openshift-3.11] Bug 1820006: CVE-2019-11-21 bump jira plugin
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1117 [release-4.5] Bug 1857550: bump jenkins to 2.235.2
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1140 Bug 1869062: fix proxy.yaml when no proxy is set
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1131 [release-4.3] Bug 1819530: update subversion plugin
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1141 [head]Smoke test
  smoke/features/README.md
  smoke/features/deployJenkinsOperator.feature
  smoke/features/environment.py
  smoke/features/requirements.txt
  smoke/features/steps/command.py
  smoke/features/steps/openshift.py
  smoke/features/steps/project.py
  smoke/features/steps/steps.py
Labels: approved, lgtm

#1143 [head]adding trigger sample pipeline scenario
  smoke/features/deployJenkinsOperator.feature
  smoke/features/requirements.txt
  smoke/features/steps/openshift.py
  smoke/features/steps/steps.py
Labels: approved, lgtm

#1142 [head] Bug 1869646: Bump Jenkins version to 2.235.5 (cve)
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1119 [release-4.4] Bug 1857549: bump jenkins to 2.235.2
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1128 [release-4.4] Bug 1857558: Bump matrix plugin
  2/Dockerfile.localdev
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
