Repository openshift/jenkins, pull requests merged in 2020-09, with the labels that each got.

#1121 [release-4.3] Bug 1857548: bump jenkins to 2.235.2
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1151 [head]Bug 1871084: oauth logout implementation
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1152 [release-4.5] Bug 1875259: Bump Jenkins version to 2.235.5 (cve)
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1155 [release 3.11] Bug 1875261: bump jenkins 2.235.5
  2/Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1160 Bug 1881477: blueocean and mailer plugins bump
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1161 Bug 1882264: bump job-dsl to 1.76
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1153 [release-4.4] Bug 1875258: 4.4 bump jenkins 2.235.5
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1133 [release-4.3] Bug 1857557: Bump matrix plugin
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1157 Bug 1883836: Update nodejs-agent imagestream to v12
  openshift/imagestreams/jenkins-agent-nodejs-rhel.json
  openshift/imagestreams/jenkins-agent-nodejs-rhel.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
