Repository openshift/jenkins, pull requests merged in 2020-06, with the labels that each got.

#1065 Fix ocp3.11 image label for rhel7
  agent-maven-3.5/Dockerfile.rhel7
  agent-nodejs-10/Dockerfile.rhel7
  agent-nodejs-12/Dockerfile.rhel7
  agent-nodejs-8/Dockerfile.rhel7
Labels: approved, lgtm

#1061 Bug 1820005: Update jira-plugin to 3.0.11+
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1069 Bug 1819997: Fixes CVE-2019-10392
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1070 3.11 jenkins 2.222.1 [openshift-3.11]
  2/Dockerfile
  2/contrib/openshift/base-plugins.txt
  2/contrib/s2i/run
Labels: approved, lgtm

#1066 Update maintainer name and Red Hat build required labels
  2/Dockerfile.rhel7
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/Dockerfile.rhel7
  agent-nodejs-10/Dockerfile.rhel7
  agent-nodejs-12/Dockerfile.rhel7
  agent-nodejs-8/Dockerfile.rhel7
  slave-base/Dockerfile.rhel7
Labels: approved, lgtm

#1072 Remove UseCGroupMemoryLimitForHeap for jnlp client as it is enable by…
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, lgtm

#1073 Bug 1813217: fix maven proxy settings
  agent-maven-3.5/contrib/bin/configure-agent
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1068 Bug 1843945: bump jenkins to 2.222.1 and update plugins
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1079 Bug 1845829: Set image version for the upgrade process
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1081 Bug 1845902: Set OPENSHIFT_JENKINS_IMAGE_VERSION
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, group-lead-approved, lgtm

#1078 Bug 1780125: fix proxy settings in jenkins
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/configuration/proxy.yaml.tpl
  2/contrib/s2i/run
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1086 OpenJDK1.8 as default for maven35 agent
  agent-maven-3.5/Dockerfile
  agent-maven-3.5/Dockerfile.rhel7
  agent-maven-3.5/contrib/bin/run-jnlp-client
  agent-maven-3.5/test/agent_maven_test.go
Labels: approved, lgtm

#1082 Bug 1847442: Set OPENSHIFT_JENKINS_IMAGE_VERSION
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1089 Bug 1849094: Use quay.io/openshift/origin-cli:4.2 as base image for upstream
  2/Dockerfile.localdev
  slave-base/Dockerfile.localdev
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1092 Bug 1848215: CVE-2020-2182: jenkins-credentials-binding-plugin 1.0.23
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1091 Bug 1848216: CVE-2020-2182 jenkins-credentials-binding-plugin 1.0.23
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1094 Removes dependency on cloudrouter repo
  2/Dockerfile.localdev
  2/contrib/openshift/CentOS-Base.repo
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/contrib/openshift/CentOS-Base.repo
  agent-nodejs-10/Dockerfile.localdev
  agent-nodejs-10/contrib/openshift/CentOS-Base.repo
  agent-nodejs-12/Dockerfile.localdev
  agent-nodejs-12/contrib/openshift/CentOS-Base.repo
  agent-nodejs-8/Dockerfile.localdev
  agent-nodejs-8/contrib/openshift/CentOS-Base.repo
  slave-base/Dockerfile.localdev
  slave-base/contrib/openshift/CentOS-Base.repo
Labels: approved, lgtm

#1067 Bug 1843941: bump jenkins to 2.222.1 and update plugins
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1087 Bug 1802297: handle ingress certificate signed by custom ca
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/configuration/logging.properties
  2/contrib/s2i/run
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1099 Bump openshift-client to 1.0.34
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm
