Repository openshift/jenkins, pull requests merged in 2020-10, with the labels that each got.

#1169 updating the scl_source enable from rh-maven35 to rh-maven36
  agent-maven-3.5/contrib/bin/scl_enable
Labels: approved, lgtm

#1156 [release-4.2] Bug 1877292: Bump Jenkins version to 2.235.5 (cve)
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1162 Bug 1881475: [3.11] Bump mailer and blueocean plugins
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1172 [openshift-3.11] Bug 1881478: bump various plugin for cve
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1173 [master] Bug 1888900: Align plugin version
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
