Repository openshift/jenkins, pull requests merged in 2020-03, with the labels that each got.

#1028 Bug 1810429: Bump login plugin to 1.0.23
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1033 Bug 1810393: 4.1 2.204.2 and plugins updates
  2/Dockerfile
  2/Dockerfile.localdev
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/s2i/run
  2/go-init/Dockerfile
  2/go-init/LICENSE
  2/go-init/README.md
  2/go-init/main.go
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/Dockerfile.rhel7
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
  slave-base/go-init/Dockerfile
  slave-base/go-init/LICENSE
  slave-base/go-init/README.md
  slave-base/go-init/main.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#1034 Bug 1813070: Bump Jenkins 2.204.2 [4.5]
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#1035 Add jkhelil as approver and reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#1027 3.11 bump jenkins 2.204.2
  2/Dockerfile
  2/Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#1038 Plugin update
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm

#1039 Revert to wildcard install of Jenkins 2 rpm
  2/Dockerfile.rhel7
Labels: approved, lgtm
