Repository openshift/jenkins, pull requests merged in 2020-04, with the labels that each got.

#1041 Bug 1819647: bump plugins script-security to 1.71, subversion to 2.13.1, workflow-…
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/valid-bug, lgtm

#1043 Support Nodejs 12 Agent
  agent-nodejs-12/Dockerfile
  agent-nodejs-12/Dockerfile.localdev
  agent-nodejs-12/Dockerfile.rhel7
  agent-nodejs-12/README.md
  agent-nodejs-12/cccp.yml
  agent-nodejs-12/contrib/bin/configure-agent
  agent-nodejs-12/contrib/bin/scl_enable
  agent-nodejs-12/test/agent_nodejs_test.go
Labels: approved, lgtm

#1044 Bug 1767806: bump jenkins to 2.222.1 and update k8s plugins
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/s2i/run
Labels: approved, bugzilla/valid-bug, lgtm

#1047 Update OWNERS with Bugzilla Component
  OWNERS
Labels: approved, lgtm

#1046 Bug 1820677: Update Description on Monitored Templates reflecting permission issues
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-persistent-monitored.json
Labels: approved, bugzilla/valid-bug, lgtm

#1045 Bug 1804345: handle ingress certificate signed by custom ca
  2/contrib/s2i/run
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#1051 Bug 1827081: Adds imagestream for jenkins-agent-base and migrates others to yaml
  openshift/imagestreams/jenkins-agent-base-centos.yaml
  openshift/imagestreams/jenkins-agent-base-rhel7.yaml
  openshift/imagestreams/jenkins-agent-maven-centos7.yaml
  openshift/imagestreams/jenkins-agent-maven-rhel7.yaml
  openshift/imagestreams/jenkins-agent-nodejs-centos7.yaml
  openshift/imagestreams/jenkins-agent-nodejs-rhel7.yaml
  openshift/imagestreams/jenkins-centos7.yaml
  openshift/imagestreams/jenkins-rhel7-ppc64le.yaml
  openshift/imagestreams/jenkins-rhel7.yaml
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#1052 Bug 1783530: set default java version to jdk 11
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
