Repository openshift/jenkins, pull requests merged in 2020-07, with the labels that each got.

#1102 Bug 1852978: Bump script-security plugin to 1.73
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1083 Bug 1847452: Set OPENSHIFT_JENKINS_IMAGE_VERSION
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1114 Bug 1857551: bump jenkins to 2.235.2
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, do-not-merge/hold, lgtm

#1110 Add Dockerfile.rhel8 throughout
  2/Dockerfile.rhel8
  agent-maven-3.5/Dockerfile.rhel8
  agent-nodejs-10/Dockerfile.rhel8
  agent-nodejs-12/Dockerfile.rhel8
  slave-base/Dockerfile.rhel8
Labels: approved, lgtm

#1115 Bug 1857560: Bump matrix plugin
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
