Repository openshift/jenkins, pull requests merged in 2020-11, with the labels that each got.

#1174 [release-4.6] Bug 1888901: Align plugin version
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1165 Updating ose-jenkins-agent-base builder & base images to be consistent with ART
  slave-base/Dockerfile.rhel8
Labels: approved, lgtm, ok-to-test

#1166 Updating ose-jenkins-agent-maven builder & base images to be consistent with ART
  agent-maven-3.5/Dockerfile.rhel8
Labels: approved, lgtm, ok-to-test

#1168 Updating ose-jenkins-agent-nodejs-12 builder & base images to be consistent with ART
  agent-nodejs-12/Dockerfile.rhel8
Labels: approved, lgtm, ok-to-test

#1167 Updating ose-jenkins-agent-nodejs-10 builder & base images to be consistent with ART
  agent-nodejs-10/Dockerfile.rhel8
Labels: approved, lgtm, ok-to-test

#1184 [master] Bug 1897584: add casc plugins
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1187 [master] Bug 1896404: various fixes
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
