Repository openshift/jenkins, pull requests merged in 2021-08, with the labels that each got.

#1281 Bug 1972361: Bump jenkins version 2.289.2
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1280 Bug 1972366: Bump jenkins version 2.289.2
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#1310 Bug 1993195: testing performance of sync plugin
  smoke/features/README.md
  smoke/features/steps/openshift.py
  smoke/features/steps/project.py
  smoke/features/steps/steps.py
  smoke/features/stress-test.feature
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1314 Bug 1995727: bump sync plugin to 1.0.49
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
