Repository openshift/jenkins, pull requests merged in 2021-02, with the labels that each got.

#1208 Bug 1923036: Fix monitored Jenkins templates display names
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-persistent-monitored.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1212 Bug 1924614: Jenkins Agent Image for maven36
  Makefile
  agent-maven-3.6/Dockerfile
  agent-maven-3.6/Dockerfile.rhel7
  agent-maven-3.6/README.md
  agent-maven-3.6/cccp.yml
  agent-maven-3.6/contrib/bin/configure-agent
  agent-maven-3.6/contrib/bin/run-jnlp-client
  agent-maven-3.6/contrib/bin/scl_enable
  agent-maven-3.6/contrib/init.gradle
  agent-maven-3.6/contrib/settings.xml
  agent-maven-3.6/test/agent_maven_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1213 Bug 1924811: Add jenkins maven36 image
  agent-maven-3.6/Dockerfile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1211 [openshift-3.11] Bug 1904308: bump jenkins plugin
  2/Dockerfile
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1207 Upgrade Jenkins to 2.263.3
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, lgtm

#1225 Bug 1928658: update kubernetes-client-api
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1227 Bug 1928845: update openshift-sync plugin
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm
