Repository openshift/jenkins, pull requests merged in 2021-01, with the labels that each got.

#1180 [openshift-3.11] Bug 1896405: Update kubernetes and mercurial plugins
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1175 [release-4.5] Bug 1896402: various fixes
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1192 [main] Bug 1904307: Update ant plugin CVE-2020-11979
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1195 Bug 1899111: Update Maven version to 3.6 in maven agent
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/Dockerfile.rhel7
  agent-maven-3.5/Dockerfile.rhel8
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1176 [release-4.4] Bug 1896401: various fixes
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
