Repository openshift/jenkins, pull requests merged in 2021-07, with the labels that each got.

#1299 Refactoring template based install test
  .gitignore
  Makefile
  scripts/test-jenkins-template-install.sh
  smoke/features/README.md
  smoke/features/deployJenkinsOperator.feature
  smoke/features/environment.py
  smoke/features/jenkins-ephemeral.feature
  smoke/features/maven-agent.feature
  smoke/features/nodejs-agent.feature
  smoke/features/plugins.feature
  smoke/features/requirements.txt
  smoke/features/steps/command.py
  smoke/features/steps/openshift.py
  smoke/features/steps/plugins.py
  smoke/features/steps/project.py
  smoke/features/steps/steps.py
  smoke/requirements.txt
  smoke/samples/maven_pipeline.yaml
  smoke/samples/nodejs_pipeline.yaml
Labels: approved, lgtm

#1300 Update README.md
  smoke/features/README.md
Labels: approved, lgtm

#1302 adding persistent template test and updating some
  smoke/features/jenkins-maven-agent.feature
  smoke/features/jenkins-nodejs-agent.feature
  smoke/features/jenkins-teardown-ephemeral.feature
  smoke/features/persistent-jenkins.feature
  smoke/features/persistent-maven-agent.feature
  smoke/features/persistent-nodejs-agent.feature
  smoke/features/steps/openshift.py
  smoke/features/steps/plugins.py
  smoke/features/steps/steps.py
Labels: approved, lgtm

#1303 Deleting the old agent feature files & updating the README.MD
  smoke/features/README.md
  smoke/features/maven-agent.feature
  smoke/features/nodejs-agent.feature
Labels: approved, lgtm

#1304 Bug 1981425: update jenkins to 2.289.2
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1306 Test the data persistence of jenkins persistent template
  smoke/features/jenkins-nodejs-agent.feature
  smoke/features/persistent-nodejs-agent.feature
  smoke/features/persistent-test.feature
  smoke/features/steps/openshift.py
  smoke/features/steps/plugins.py
  smoke/features/steps/steps.py
Labels: approved, lgtm

#1297 Bug 1925524: bump k8s plugin to 1.30 to enable 1.0.48 release of openshift sync plugin
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1307 Bug 1974338: Update README.md with USE_JAVA_VERSION env var explanation
  README.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1282 Bug 1972354: Bump jenkins version 2.289.2
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm, qe-approved
