Repository openshift/jenkins, pull requests merged in 2021-05, with the labels that each got.

#1263 Bug 1956220: add proxy system properties as expected by kubernetes-client
  2/contrib/openshift/base-plugins.txt
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1265 [release-4.7] Bug 1952562: bump config-file-provider to 3.7.1
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1259 [release 4.7] Bug 1947810: Update Jenkins to 2.277.3 and disable setup wizard
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1260 [release 4.6] Bug 1952337: Update Jenkins to 2.277.3 and disable setup wizard
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1271 [release 4.8] Bug 1960019: Bump credentials plugin to 2.3.19
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
