Repository openshift/jenkins, pull requests merged in 2021-11, with the labels that each got.

#1331 Bug 2015085: update git plugin to version 4.8.3
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1332 Bug 2020616: update jenkins version to 2.303.3 (security update)
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent, qe-approved

#1337 Bug 2020610: Update subversion plugin to 2.15.1
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1344 Fixes #1241
  2/contrib/s2i/run
Labels: lgtm, approved, ok-to-test

#1345 Bug 2003204: Fix jbcrypt_path lookup and add openshift enable oauth env support
  2/Dockerfile.localdev
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/jenkins/jenkins-common.sh
  2/contrib/s2i/run
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1346 [release-4.9] Bug 2020615: Update Jenkins and plugins per 2021-11 advisory
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#1349 [release-4.6] Bug 2020612: Update Jenkins and plugins per 2021-11 advisory
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#1348 [release-4.7] Bug 2020613: Update Jenkins and plugins per 2021-11 advisory
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#1347 [release-4.8] Bug 2020614: Update Jenkins and plugins per 2021-11 advisory
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#1351 [release-3.11] Bug 2020611: Update Jenkins and plugins per 2021-11 advisory
  2/Dockerfile
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent, backport-risk-assessed

#1353 Change smoke tests so they can run in openshift-ci
  scripts/test-jenkins-template-install.sh
  smoke/features/jenkins-maven-agent.feature
  smoke/features/jenkins-nodejs-agent.feature
  smoke/features/jenkins-teardown-ephemeral.feature
  smoke/features/persistent-maven-agent.feature
  smoke/features/steps/steps.py
Labels: lgtm, approved
