Repository openshift/jenkins, pull requests merged in 2021-06, with the labels that each got.

#1266 [release-4.6] Bug 1952561: bump config-file-provider to 3.7.1
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1275 Remove hard dependency on kubernetes-client-api
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm

#1262 [release 4.5] Bug 1952340: Jenkins 2.277.3 update and disable setup wizard
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1267 [release-4.5] Bug 1952560: bump config-file-provider to 3.7.1
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#1273 Bug 1973109: Fixed MAVEN _VERSION env var
  agent-maven-3.6/Dockerfile.rhel7
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm, ok-to-test

#1289 Bug 1973123: Add jkhelil to 3.11 OWNERS
  OWNERS
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#1274 [release-3.11] Bug 1952564: bump config-file-provider to 3.7.1
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1283 Bug 1972351: Bump jenkins version 2.289.1
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1276 Bug 1970962: Remove dependency to acegi-security in favor of jbcrypt (because aceg…
  2/contrib/jenkins/jenkins-common.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/password-encoder.jar
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1268 Nuke custom credentials for kubernetes-plugin
  2/contrib/jenkins/kube-slave-common.sh
  2/contrib/openshift/configuration/credentials.xml.tpl
  2/contrib/s2i/run
Labels: approved, lgtm

#1294 Upgrade various plugins to prepare openshift-sync 1.0.47
  2/contrib/openshift/base-plugins.txt
Labels: approved, lgtm

#1269 Bug 1972451: Correctly declare Jenkins URL with trailing slash
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#1019 Bug 1971537: Support cgroups v2
  2/contrib/s2i/run
  agent-maven-3.5/contrib/bin/configure-agent
  slave-base/contrib/bin/run-jnlp-client
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, size/M

#1295 [3.11] Bug 1929718: Openshift 3.11 Various fixes
  2/Dockerfile
  2/contrib/jenkins/jenkins-common.sh
  2/contrib/jenkins/kube-slave-common.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/password-encoder.jar
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1291 Move call to create_jenkins_location_configuration_xml after image_co…
  2/contrib/s2i/run
Labels: approved, lgtm

#1298 [maven] Remove maven 3.5 dir to enforce maven to be version agnostic
  agent-maven-3.5/Dockerfile
  agent-maven-3.5/Dockerfile.localdev
  agent-maven-3.5/Dockerfile.rhel7
  agent-maven-3.5/Dockerfile.rhel8
  agent-maven-3.5/README.md
  agent-maven-3.5/cccp.yml
  agent-maven-3.5/contrib/bin/configure-agent
  agent-maven-3.5/contrib/bin/scl_enable
  agent-maven-3.5/contrib/openshift/CentOS-Base.repo
  agent-maven-3.5/contrib/settings.xml
  agent-maven-3.5/test/agent_maven_test.go
  agent-maven/Dockerfile.localdev
  agent-maven/contrib/bin/configure-agent
Labels: approved, lgtm
