Repository openshift/jenkins, pull requests merged in 2021-04, with the labels that each got.

#1251 [4.8] Bug 1940558: Update matrix-auth plugin to 2.6.6
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1232 [release 4.5] Bug 1929120: update kubernetes-client-api
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1249 [4.8] Bug 1947358: Update jenkins to 2.277.2
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1250 [3.11] Bug 1947359 : Update Jenkins version to 2.277.2
  2/Dockerfile
Labels: approved, lgtm

#1257 Bug 1950384: Revert "Update jenkins to 2.277.2"
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1246 Bug 1950175: Build with Go 1.16
  2/Dockerfile.rhel8
  slave-base/Dockerfile.rhel8
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1258 Bug 1940558: Update Jenkins to 2.277.3 and disable startup wizard
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/s2i/run
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1226 [head] Bug 1929052: Add missing backslash to agent maven dockerfile
  agent-maven-3.5/Dockerfile.localdev
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#1261 Bug 1891694: Update Jenkins to 2.277.3 and disable setup wizard
  2/Dockerfile
  2/contrib/s2i/run
Labels: approved, lgtm

#1236 [openshift-3.11] Bug 1929718: update kubernetes-client-api
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1264 [release-4.8] Bug 1952563: bump config-file-provider to 3.7.1
  2/contrib/openshift/base-plugins.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
