Repository openshift/jenkins, pull requests merged in 2021-12, with the labels that each got.

#1354 Smoke test for JENKINS_PASSWORD
  smoke/features/jenkins-ephemeral-without-oauth.feature
  smoke/features/jenkins-teardown-ephemeral.feature
  smoke/features/persistent-test.feature
  smoke/features/steps/build_steps.py
  smoke/features/steps/command.py
  smoke/features/steps/debug.py
  smoke/features/steps/delete_steps.py
  smoke/features/steps/deployment_steps.py
  smoke/features/steps/env_var_steps.py
  smoke/features/steps/login_steps.py
  smoke/features/steps/openshift.py
  smoke/features/steps/project.py
  smoke/features/steps/steps.py
  smoke/features/steps/template_steps.py
  smoke/features/steps/volume_steps.py
  smoke/features/stress-test.feature
  smoke/requirements.txt
Labels: lgtm, approved

#1356 refactoring smoke test
  smoke/features/README.md
  smoke/features/jenkins-ephemeral.feature
  smoke/features/plugins.feature
  smoke/features/steps/build_steps.py
Labels: lgtm, approved

#1355 JKNS-257: add java/nodejs sidecar pod templates examples
  2/contrib/jenkins/kube-slave-common.sh
  README.md
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
Labels: lgtm, approved

#1350 Use groupified apiVersion
  example-plugin-development-template.yaml
  openshift/imagestreams/jenkins-agent-base-centos.yaml
  openshift/imagestreams/jenkins-agent-base-rhel.yaml
  openshift/imagestreams/jenkins-agent-maven-centos.json
  openshift/imagestreams/jenkins-agent-maven-centos.yaml
  openshift/imagestreams/jenkins-agent-maven-rhel.json
  openshift/imagestreams/jenkins-agent-maven-rhel.yaml
  openshift/imagestreams/jenkins-agent-nodejs-centos.json
  openshift/imagestreams/jenkins-agent-nodejs-centos.yaml
  openshift/imagestreams/jenkins-agent-nodejs-rhel.json
  openshift/imagestreams/jenkins-agent-nodejs-rhel.yaml
  openshift/imagestreams/jenkins-centos.json
  openshift/imagestreams/jenkins-centos.yaml
  openshift/imagestreams/jenkins-rhel.json
  openshift/imagestreams/jenkins-rhel.yaml
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
  smoke/samples/maven_pipeline.yaml
  smoke/samples/nodejs_pipeline.yaml
Labels: lgtm, approved

#1358 Bug 2016058: Bump openshift-sync-plugin to 1.0.51 and various dependant plugins
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1352 Bug 2003204: Fix the admin startup on ephemeral volume initial password case
  2/contrib/s2i/run
  2/test/jenkins_test.go
  Makefile
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
