Repository openshift/jenkins, pull requests merged in 2022-03, with the labels that each got.

#1399 Removing non-blocker test for 4.10 interop
  smoke/features/jenkins-ephemeral-without-oauth.feature
  smoke/features/jenkins-ephemeral.feature
  smoke/features/steps/login_steps.py
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1400 Update OWNERS
  OWNERS
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1395 Bug 2054816: Bump openshift-client plugin to 1.0.37
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1402 Bug 2058752: 2022-02-15 Security Advisory
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, px-approved, docs-approved

#1394 Sort final plugins list alphabetically in `make plugins-list`
  2/contrib/jenkins/install-plugins.sh
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1384 JNKS-269: Use the generated bundle-plugins.txt file while building the image
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1404 switch to 'sort -d' for consistent sort across linux variants
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1401 Bug 2062053: Add Jitendar to OWNERS file
  OWNERS
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, px-approved, docs-approved, qe-approved, backport-risk-assessed

#1312 Add support for websocket connection to Jenkins
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, ok-to-test, px-approved, docs-approved, qe-approved

#1403 Bug 2063898: [release-4.10] 2022-02-15 Security Advisory
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1406 Bug 2058751: [release-4.9] 2022-02-15 Security Advisory
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1408 Bug 2058750: [release-4.8] 2022-02-15 Security Advisory
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1396 JKNS-271 : Adding Test case Ids to ease polarion integration for jenkins
  smoke/features/jenkins-ephemeral.feature
  smoke/features/jenkins-maven-agent.feature
  smoke/features/jenkins-nodejs-agent.feature
  smoke/features/jenkins-teardown-ephemeral.feature
  smoke/features/persistent-jenkins.feature
  smoke/features/persistent-maven-agent.feature
  smoke/features/persistent-nodejs-agent.feature
  smoke/features/persistent-test.feature
  smoke/features/sidecar-pattern-jenkins.feature
  smoke/features/stress-test.feature
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1413 Bug 2067128: [release-4.9] compute bundle plugins in build
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
  Makefile
  hack/build.sh
  hack/check-plugins-supply-chain-change.sh
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1417 Bug 2069134: [release-4.10] Enable supply-chain check
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1415 Bug 2069142: [release-4.7] 2022-02-15 Security Advisory
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1421 Bug 2066019: set necessary JVM args to allow jenkins JVM to come up on a FIPS node
  2/contrib/s2i/run
  README.md
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
