Repository openshift/jenkins, pull requests merged in 2022-04, with the labels that each got.

#1420 Bug 2069134: [release-4.10] Update bundle-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1422 Bug 2069498: [release-4.9] update bundle plugins
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#1416 Bug 2069143: [release-4.6] 2022-02-15 Security Advisory
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1424 Bug 2058747: Update base-plugins.txt
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1427 Bug 2058794: Bump Jenkins LTS Version
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1428 Bug 2076257: Multiple Fixes
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1426 Bug 2058793: Jenkins fix for CVE-2021-43859
  2/Dockerfile
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1431 Bug 2076430: Mitigate multiple CVEs
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1429 [release-3.11] Bug 2076243: Multiple fixes
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1430 [release-4.10] Bug 2076253: Mitigate multiple CVEs
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1434 JKNS-289: complete switch from ocp payload to cpaas images for both jenkins and base agent ocp images
  openshift/imagestreams/jenkins-agent-base-rhel.json
  openshift/imagestreams/jenkins-agent-base-rhel.yaml
  openshift/imagestreams/jenkins-rhel.json
  openshift/imagestreams/jenkins-rhel.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1433 Bug 2077289: set necessary JVM args to allow jenkins JVM to come up on a FIPS node
  2/contrib/s2i/run
  README.md
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1438 JNKS-287: cannot use specific image refs with okd; quay.io prunes too often
  openshift/imagestreams/jenkins-centos.json
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1440 Bug 1972451: Correctly declare Jenkins URL with trailing slash
  2/contrib/s2i/run
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1439 Bug 2078477: set necessary JVM args to allow jenkins JVM to come up on a FIPS node
  2/contrib/s2i/run
  README.md
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed
