Repository openshift/jenkins, pull requests merged in 2022-05, with the labels that each got.

#1442 JNKS-289: return agent-maven / agent-nodejs imagestreams
  openshift/imagestreams/jenkins-agent-maven-ocp.json
  openshift/imagestreams/jenkins-agent-maven-okd.json
  openshift/imagestreams/jenkins-agent-nodejs-ocp.json
  openshift/imagestreams/jenkins-agent-nodejs-okd.json
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1443 JNKS-289: fix jenkins okd '2' tag
  openshift/imagestreams/jenkins-centos.json
  openshift/imagestreams/jenkins-centos.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1435 [release-4.8] Bug 2076251: Mitigate multiple CVEs
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1436 [release-4.7] Bug 2076250: Mitigate multiple CVEs
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1450 Bug 2088388: refactoring test for interop testing failures
  smoke/features/jenkins-teardown-ephemeral.feature
  smoke/features/steps/build_steps.py
  smoke/features/steps/delete_steps.py
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#1437 [release-4.6] Bug 2076249: Mitigate multiple CVEs
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed
