Repository openshift/jenkins, pull requests merged in 2022-10, with the labels that each got.

#1490 OCPBUGS-1942: Bump Jenkins version to 2.361.1
  2/Dockerfile.rhel7
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1489 [release-4.9] OCPBUGS-1811: update install plugins script
  2/contrib/jenkins/install-plugins.sh
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#1495 OCPBUGS-2099: Force git-server to an earlier version
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  OWNERS
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1488 [release-4.9] OCPBUGS-1757: Install glibc language package to remove `setLocale` warning
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug

#1497 Add Bharat as Approver & Reviewer
  OWNERS
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1500 OCPBUGS-2184: Bump jenkins-client-plugin to version 1.0.38
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1502 OCPBUGS-1870: CVE-2022-25857 Mitigation
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1506 OCPBUGS-914: Add maven plugin dependency
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1508 OCPBUGS-903: Bump openshift-login plugin to 1.0.29
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1478 [release-4.10] OCPBUGS-724: Update blueocean-autofavorite to 1.2.5
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug
