Repository openshift/jenkins, pull requests merged in 2022-09, with the labels that each got.

#1479 [release-4.10] OCPBUGS-473: CVE mitigations
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
  Makefile
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#1480 [release-4.10] OCPBUGS-1037: Install glibc language package to remove `setLocale` warning
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug

#1483 [release-4.11] OCPBUGS-1438: fix install plugins
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#1486 OCPBUGS-1709: Sync javax-mail-api with version required by jenkins 2.346.3
  2/Dockerfile.localdev
  2/contrib/openshift/CentOS-Base.repo
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1484 [release-4.10] OCPBUGS-1440: fix install plugins script
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug
