Repository openshift/jenkins, pull requests merged in 2022-01, with the labels that each got.

#1359 Bug 2037346: Update openshift-sync-plugin to 1.0.51 and various dependant plugins
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1360 Bug 2037348: Update openshift-sync-plugin to 1.0.51 and various dependant plugins
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1361 Bug 2034839: bump sync plugin to 1.0.52
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1364 testing sidecar pattern for jenkins pod template
  smoke/features/sidecar-pattern-jenkins.feature
  smoke/samples/java-builder-cm.yaml
  smoke/samples/nodejs-builder-cm.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1368 Bug 2044942: Jenkins Fixes for CVE-2022-20617 and CVE-2022-20612
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1369 Bug 2044941: Jenkins Fixes for CVE-2022-20617 and CVE-2022-20612
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, qe-approved, backport-risk-assessed

#1375 Bug 2041888: bump openshift-sync to 1.0.53
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
