Repository openshift/jenkins, pull requests merged in 2022-12, with the labels that each got.

#1532 OCPBUGS-4520: Update jenkins master branch to use 4.13 base image
  .ci-operator.yaml
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  agent-nodejs-12/Dockerfile.rhel8
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1531 [release-4.9] OCPBUGS-4321: Bump jenkins version to 2.361.1
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1530 [release-4.10] OCPBUGS-912: Add maven plugin dependency in base plugins
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1461 Update install-plugins.sh
  2/contrib/jenkins/install-plugins.sh
Labels: lgtm, approved, ok-to-test, px-approved, docs-approved, qe-approved

#1527 OCPBUGS-4094: Various CVEs September/2022
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1511 [release-4.8] OCPBUGS-475: Release 4.8 august CVE mitigations
  2/Dockerfile.rhel7
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel7
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#1528 [master] OCPBUGS-4129: various plugins bumps
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1516 OCPBUGS-4694: Handle OPENSHIFT_ENABLE_OAUTH properly
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/s2i/run
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug
