Repository openshift/jenkins, pull requests merged in 2022-11, with the labels that each got.

#1507 [release-4.11] OCPBUGS-913: Add maven plugin dependency in base plugins
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1512 [release-4.9] OCPBUGS-3173: Add glibc-langpack-en package in agent-base image
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug

#1519 Update OWNERS
  OWNERS
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1523 OCPBUGS-3692: [release-4.12] Update OWNERS
  OWNERS
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#1521 OCPBUGS-3697: [release-4.10] Update OWNERS
  OWNERS
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug

#1520 OCPBUGS-3698: [release-4.9] Update OWNERS
  OWNERS
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug

#1524 OCPBUGS-3760: [release-4.8] Update OWNERS
  OWNERS
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug

#1526 [release-4.8] OCPBUGS-4131: Externalize jenkins-version
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
  Makefile
  hack/build.sh
  hack/check-plugins-supply-chain-change.sh
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug
