Repository openshift/jenkins, pull requests merged in 2022-02, with the labels that each got.

#1376 Bug 2047839: Upgrade Jenkins plugins to fix various flaws
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1371 Bug 2044939: Jenkins Fixes for CVE-2022-20617 and CVE-2022-20612
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1372 Bug 2044938: Jenkins Fixes for CVE-2022-20617 and CVE-2022-20612
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1374 JKNS-269: Pre-compute bundle-plugins.txt
  2/Dockerfile.localdev
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
  Makefile
  hack/build.sh
  hack/check-plugins-supply-chain-change.sh
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1382 JNKS-269: Adds git pre-commit hook
  .githooks/pre-commit
  CONTRIBUTING.md
  README.md
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1373 Bug 2044943: Jenkins Fixes for CVE-2022-20617 and CVE-2022-20612
  2/Dockerfile
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1383 steps definition for sidecar-pattern-jenkins feature
  smoke/features/jenkins-ephemeral-without-oauth.feature
  smoke/features/jenkins-ephemeral.feature
  smoke/features/jenkins-maven-agent.feature
  smoke/features/jenkins-nodejs-agent.feature
  smoke/features/persistent-jenkins.feature
  smoke/features/persistent-maven-agent.feature
  smoke/features/persistent-nodejs-agent.feature
  smoke/features/sidecar-pattern-jenkins.feature
  smoke/features/steps/build_steps.py
  smoke/features/steps/openshift.py
  smoke/features/steps/plugins.py
  smoke/features/steps/steps.py
  smoke/requirements.txt
  smoke/samples/nodejs_pipeline.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1390 removing reference to plugin class
  smoke/features/steps/steps.py
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1365 Bug 2055650: Add xmlstarlet to handle JENKINS_PASSWORD properly
  2/Dockerfile.rhel7
  2/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1393 Bug 2054822: allow Pipeline Utility Steps (2.12.0) to start
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
