Repository openshift/jenkins, pull requests merged in 2022-06, with the labels that each got.

#1453 Bug 2095620: Bump matrix-project plugin to 1.20
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#1454 update contributing guide for e2e changes, payload removal and new process
  CONTRIBUTING.md
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1455 update imagestream image refs as needed based on recent CPaaS updates
  openshift/imagestreams/jenkins-agent-base-centos.yaml
  openshift/imagestreams/jenkins-rhel.json
  openshift/imagestreams/jenkins-rhel.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1451 Bug 2096207: Add missing glibc-langpack-en for specified locale
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, bugzilla/severity-unspecified, qe-approved

#1444 Bug 2096186: Avoid double slashes trailing in remoting.jar
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
