Repository openshift/jenkins, pull requests merged in 2023-05, with the labels that each got.

#1666 Updating to the latest(ish) plugin versions
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
  2/contrib/s2i/run
  Makefile
  scripts/build-development-images.sh
  scripts/jenkins-script-console.txt
  scripts/verify.sh
  slave-base/Dockerfile.rhel8
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1668 Fixing/updating smoke tests with removal of nodejs and maven images
  .gitignore
  .pylintrc
  scripts/test-jenkins-template-install.sh
  smoke/README.md
  smoke/features/jenkins-ephemeral.feature
  smoke/features/jenkins-teardown-ephemeral.feature
  smoke/features/persistent-jenkins.feature
  smoke/features/persistent-test.feature
  smoke/features/sidecar-pattern-jenkins.feature
  smoke/features/steps/steps.py
  smoke/features/stress-test.feature
  smoke/requirements.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1672 [release-4.10] OCPBUGS-13654: Bump Jenkins version and Plugin versions
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-jenkins-core-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
  agent-maven/Dockerfile.rhel8
  agent-nodejs-10/Dockerfile.rhel8
  agent-nodejs-12/Dockerfile.rhel8
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/invalid-bug, jira/severity-important, jira/valid-reference

#1673 OCPBUGS-13869: Mitigate CVEs and other updates
  2/Dockerfile.rhel8
  2/contrib/jenkins/install-plugins.sh
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, px-approved, docs-approved, qe-approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1675 mitigate CVEs
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, cherry-pick-approved, px-approved, docs-approved, qe-approved, backport-risk-assessed

#1678 OCPBUGS-14111: Update to use 4.13 ImageStreams
  openshift/imagestreams/jenkins-agent-base-centos.json
  openshift/imagestreams/jenkins-agent-base-centos.yaml
  openshift/imagestreams/jenkins-agent-base-rhel.json
  openshift/imagestreams/jenkins-agent-base-rhel.yaml
  openshift/imagestreams/jenkins-centos.json
  openshift/imagestreams/jenkins-centos.yaml
  openshift/imagestreams/jenkins-rhel.json
  openshift/imagestreams/jenkins-rhel.yaml
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1680 [release-4.12] OCPBUGS-14113: Update to use new images
  openshift/imagestreams/jenkins-agent-base-rhel.json
  openshift/imagestreams/jenkins-agent-base-rhel.yaml
  openshift/imagestreams/jenkins-rhel.json
  openshift/imagestreams/jenkins-rhel.yaml
Labels: lgtm, approved, cherry-pick-approved, px-approved, docs-approved, qe-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1667 Docs: fixed behavior of OVERRIDE_RELEASE_MIGRATION_OVERWRITE env var
  README.md
Labels: lgtm, approved, needs-ok-to-test, px-approved, docs-approved, qe-approved

#1683 OCPBUGS-14287: Update plugins to latest available
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1682 [release-4.10] OCPBUGS-14279: Updates to use Java 11 by default
  2/Dockerfile.rhel8
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/invalid-bug, jira/valid-reference

#1685 OCPBUGS-14363: Update Jenkins to 2.401.1 LTS and bump plugins
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1686 [release-4.13] OCPBUGS-14311:Combined backport updates
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
  README.md
Labels: lgtm, approved, cherry-pick-approved, px-approved, docs-approved, qe-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference
