Repository openshift/jenkins, pull requests merged in 2023-02, with the labels that each got.

#1569 [release-4.10] OCPBUGS-4095: Required Plugin `workflow-multibranch`
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1571 [release-4.8] OCPBUGS-6934: Make hack/check-plugins-supply-chain-change.sh executable
  hack/check-plugins-supply-chain-change.sh
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1568 OCPBUGS-6870: Bump Jenkins version to 2.361.4
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1573 [release-4.11] OCPBUGS-4439: Mitigating CVE-2022-1471
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1544 [release-4.9] OCPBUGS-4111: Various CVEs September/2022
  2/Dockerfile.localdev
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1580 [release-4.12] OCPBUGS-7050: Sync jenkins version and plugins with ma…
  2/contrib/openshift/base-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1581 [release-4.11] OCPBUGS-7051: Sync jenkins version and plugins with ma…
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1582 [release-4.10] OCPBUGS-7052: Sync jenkins version and plugins with ma…
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/invalid-bug, jira/severity-important, jira/valid-reference

#1583 [release-4.9] OCPBUGS-7053: Sync jenkins version and plugins with mas…
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/invalid-bug, jira/severity-important, jira/valid-reference

#1584 [release-4.8] OCPBUGS-7054: Sync jenkins version and plugins with mas…
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/invalid-bug, jira/severity-important, jira/valid-reference

#1587 [release-4.10] OCPBUGS-7238: Enable Websocket support
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1588 Bump jenkins image version to use 4.12
  openshift/imagestreams/jenkins-agent-base-centos.json
  openshift/imagestreams/jenkins-agent-base-centos.yaml
  openshift/imagestreams/jenkins-agent-base-rhel.json
  openshift/imagestreams/jenkins-agent-base-rhel.yaml
  openshift/imagestreams/jenkins-centos.json
  openshift/imagestreams/jenkins-centos.yaml
  openshift/imagestreams/jenkins-rhel.json
  openshift/imagestreams/jenkins-rhel.yaml
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1589 [release-4.12] bump jenkins images 4.12
  openshift/imagestreams/jenkins-agent-base-centos.json
  openshift/imagestreams/jenkins-agent-base-centos.yaml
  openshift/imagestreams/jenkins-agent-base-rhel.json
  openshift/imagestreams/jenkins-agent-base-rhel.yaml
  openshift/imagestreams/jenkins-agent-maven-ocp.json
  openshift/imagestreams/jenkins-agent-maven-okd.json
  openshift/imagestreams/jenkins-agent-nodejs-ocp.json
  openshift/imagestreams/jenkins-agent-nodejs-okd.json
  openshift/imagestreams/jenkins-centos.json
  openshift/imagestreams/jenkins-centos.yaml
  openshift/imagestreams/jenkins-rhel.json
  openshift/imagestreams/jenkins-rhel.yaml
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed
