Repository openshift/jenkins, pull requests merged in 2023-04, with the labels that each got.

#1645 OCPBUGS-11254: Fix several open issues on github
  2/contrib/jenkins/kube-slave-common.sh
  2/contrib/s2i/run
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#1650 OCPBUGS-11158,OCPBUGS-7575,OCPBUGS-7572: Various issues
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#1654 OCPBUGS-11446: Update config-file-provider plugin
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1656 update verify-jenkins script to show version numbers in output
  scripts/verify-jenkins.sh
Labels: approved

#1660 [JKNS-345] Remove all legacy pieces from Jenkins repository
  Makefile
  agent-maven/Dockerfile
  agent-maven/Dockerfile.localdev
  agent-maven/Dockerfile.rhel7
  agent-maven/Dockerfile.rhel8
  agent-maven/README.md
  agent-maven/cccp.yml
  agent-maven/contrib/bin/configure-agent
  agent-maven/contrib/bin/scl_enable
  agent-maven/contrib/openshift/CentOS-Base.repo
  agent-maven/contrib/settings.xml
  agent-maven/test/agent_maven_test.go
  agent-nodejs-10/Dockerfile
  agent-nodejs-10/Dockerfile.localdev
  agent-nodejs-10/Dockerfile.rhel7
  agent-nodejs-10/Dockerfile.rhel8
  agent-nodejs-10/README.md
  agent-nodejs-10/cccp.yml
  agent-nodejs-10/contrib/bin/configure-agent
  agent-nodejs-10/contrib/bin/scl_enable
  agent-nodejs-10/contrib/openshift/CentOS-Base.repo
  agent-nodejs-10/test/agent_nodejs_test.go
  agent-nodejs-12/Dockerfile
  agent-nodejs-12/Dockerfile.localdev
  agent-nodejs-12/Dockerfile.rhel7
  agent-nodejs-12/Dockerfile.rhel8
  agent-nodejs-12/README.md
  agent-nodejs-12/cccp.yml
  agent-nodejs-12/contrib/bin/configure-agent
  agent-nodejs-12/contrib/bin/scl_enable
  agent-nodejs-12/contrib/openshift/CentOS-Base.repo
  agent-nodejs-12/test/agent_nodejs_test.go
  agent-nodejs-8/Dockerfile
  agent-nodejs-8/Dockerfile.localdev
  agent-nodejs-8/Dockerfile.rhel7
  agent-nodejs-8/README.md
  agent-nodejs-8/cccp.yml
  agent-nodejs-8/contrib/bin/configure-agent
  agent-nodejs-8/contrib/bin/scl_enable
  agent-nodejs-8/contrib/openshift/CentOS-Base.repo
  agent-nodejs-8/test/agent_nodejs_test.go
  hack/build.sh
  openshift/imagestreams/jenkins-agent-maven-ocp.json
  openshift/imagestreams/jenkins-agent-maven-okd.json
  openshift/imagestreams/jenkins-agent-nodejs-ocp.json
  openshift/imagestreams/jenkins-agent-nodejs-okd.json
  slave-base/Dockerfile.rhel7
  smoke/features/jenkins-maven-agent.feature
  smoke/features/jenkins-nodejs-agent.feature
  smoke/features/persistent-maven-agent.feature
  smoke/features/persistent-nodejs-agent.feature
  smoke/samples/maven_pipeline.yaml
  smoke/samples/nodejs-builder-cm.yaml
  smoke/samples/nodejs_pipeline.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1663 Verify installed packages against Dockerfile.rhel8
  scripts/verify-jenkins.sh
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1662 [JKNS-344] Second phase of self-verification process for Jenkins
  scripts/verify-jenkins-on-openshift.sh
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
