Repository openshift/jenkins, pull requests merged in 2023-10, with the labels that each got.

#1717 fixes for localdev
  2/Dockerfile.localdev
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1718 updating to go-1.20 and ocp-4.15
  .ci-operator.yaml
  2/Dockerfile.rhel8
  go.mod
  slave-base/Dockerfile.rhel8
Labels: approved

#1719 updating to go-1.20 and ocp-4.14
  .ci-operator.yaml
  2/Dockerfile.rhel8
  go.mod
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved

#1711 OCPTOOLS-243: Bump jenkins to 2.414.3
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, jira/valid-reference

#1722 [release-4.14] OCPTOOLS-244: Bump jenkins to 2.414.3
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, jira/valid-reference

#1723 [release-4.13] OCPBUGS-21629: git-init: fix NPE when killing a process
  2/go-init/main.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1724 [release-4.12] OCPBUGS-21617: git-init: fix NPE when killing a process
  2/go-init/main.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1729 [release-4.11] OCPTOOLS-247: Bump jenkins to 2.414.3
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1726 [release-4.13] OCPTOOLS-245: Bump jenkins to 2.414.3
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1728 [release-4.12] OCPTOOLS-246: Bump jenkins to 2.414.3
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1725 [release-4.11] OCPBUGS-21632: git-init: fix NPE when killing a process
  2/go-init/main.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
