Repository openshift/jenkins, pull requests merged in 2023-01, with the labels that each got.

#1539 [release-4.9] OCPBUGS-911: Add maven plugin in base plugins
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1549 [release-4.12] OCPBUGS-4093: Various CVEs September/2022
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#1555 OCPBUGS-6579: Update sample imagestreams with latest 4.11 image using specific image tag reference
  openshift/imagestreams/jenkins-agent-base-rhel.json
  openshift/imagestreams/jenkins-agent-base-rhel.yaml
  openshift/imagestreams/jenkins-rhel.json
  openshift/imagestreams/jenkins-rhel.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1548 [release-4.11] OCPBUGS-6648: Various CVEs September/2022
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1561 [release-4.10] OCPBUGS-900: Bump openshift login plugin to 1.0.29
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1564 [release-4.9] OCPBUGS-6711: Force git server to an earlier version
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1547 [release-4.10] OCPBUGS-4095: Various CVEs September/2022
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
