Repository openshift/jenkins, pull requests merged in 2023-03, with the labels that each got.

#1578 OCPBUGS-7030: Mitigate CVE-2023-24422 - script-security
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1585 OCPBUGS-7239: Add git-lfs package
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1586 OCPBUGS-7233: Make Java 11 the default
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1590 OCPBUGS-8346: updating to use go1.19
  go.mod
  go.sum
  vendor/github.com/Microsoft/go-winio/go.mod
  vendor/github.com/Microsoft/go-winio/go.sum
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/nxadm/tail/go.mod
  vendor/github.com/nxadm/tail/go.sum
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/opencontainers/go-digest/go.mod
  vendor/golang.org/x/xerrors/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#1595 OCPBUGS-8295: Add glibc-locale-source package
  2/Dockerfile.rhel8
  slave-base/Dockerfile.rhel7
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#1607 [release-4.13] OCPBUGS-8360: Bump script-security plugin
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#1606 [release-4.13] OCPBUGS-8292: Add glibc-locale-source package
  2/Dockerfile.rhel8
  slave-base/Dockerfile.rhel7
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1593 OCPBUGS-8437: Fix labels for jenkins-slave-base-rhel8
  2/Dockerfile.rhel8
  agent-maven/Dockerfile.rhel8
  agent-nodejs-10/Dockerfile.rhel8
  agent-nodejs-12/Dockerfile.rhel8
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1594 OCPBUGS-2541: configuration-as-code bumped to 1569.vb_72405b_80249
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1613 OCPBUGS-8295: Define local env to suppress LOCALE warning
  slave-base/Dockerfile.rhel7
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#1614 [release-4.13] OCPBUGS-8292: Define local env to suppress LOCALE warning
  slave-base/Dockerfile.rhel7
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1591 [release-4.12] OCPBUGS-8420: update to use go1.18
  go.mod
  go.sum
  vendor/github.com/Microsoft/go-winio/go.mod
  vendor/github.com/Microsoft/go-winio/go.sum
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/nxadm/tail/go.mod
  vendor/github.com/nxadm/tail/go.sum
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/opencontainers/go-digest/go.mod
  vendor/golang.org/x/xerrors/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1592 [release-4.11] OCPBUGS-8423: update to go1.17
  go.mod
  go.sum
  vendor/github.com/Microsoft/go-winio/go.mod
  vendor/github.com/Microsoft/go-winio/go.sum
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/nxadm/tail/go.mod
  vendor/github.com/nxadm/tail/go.sum
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/opencontainers/go-digest/go.mod
  vendor/golang.org/x/xerrors/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1623 Add scripts/verify-jenkins.sh file
  scripts/verify-jenkins.sh
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1624 [release-4.10] OCPBUGS-6627: Bump script security plugin
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1626 Update README.md
  README.md
Labels: approved

#1628 Update OWNERS
  OWNERS
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1629 OCPBUGS-10917: Bump Jenkins version to 2.387.1
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#1625 [release-4.9] OCPBUGS-6626: Bump script security plugin
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/invalid-bug, jira/valid-reference

#1632 [release-4.9] OCPBUGS-2540: Mitigate CVE-2022-42889
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: approved, cherry-pick-approved, backport-risk-assessed, jira/invalid-bug, jira/valid-reference
