Repository openshift/jenkins, pull requests merged in 2024-09, with the labels that each got.

#1842 Add JDK 17
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
Labels: approved

#1846 Fix java alternatives
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  2/contrib/openshift/jenkins-version.txt
  2/contrib/s2i/run
  BASIC_USAGE.md
  scripts/verify-jenkins.sh
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1849 [release-4.13] Fix java alternatives
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  2/contrib/s2i/run
  ADVANCED_USAGE.md
  BASIC_USAGE.md
  BUILDING.md
  CHANGELOG.md
  CONTRIBUTING.md
  PLUGINS.md
  README.md
  SECURITY.md
  TESTING.md
  scripts/verify-jenkins.sh
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed

#1851 [release-4.12] Add java 17
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  2/contrib/s2i/run
  ADVANCED_USAGE.md
  BASIC_USAGE.md
  BUILDING.md
  CHANGELOG.md
  CONTRIBUTING.md
  PLUGINS.md
  README.md
  SECURITY.md
  TESTING.md
  scripts/verify-jenkins.sh
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed
