Repository openshift/jenkins, pull requests merged in 2024-04, with the labels that each got.

#1772 OCPTOOLS-296: CVE-2024-23900
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, jira/valid-reference

#1775 add avinal, ramessesii2, ayushsatyam146 to the Owners
  OWNERS
Labels: lgtm, approved

#1770 JKNS-398 : Bump Jenkins version to 2.440.3
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved

#1773 OCPTOOLS-393: Revert Incomplete Template Update
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent.json
  smoke/features/steps/openshift.py
Labels: lgtm, approved, jira/valid-reference

#1771 OCPTOOLS-340: Fix CVE-2024-23899
  .gitignore
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-reference

#1776 OCPTOOLS-322: Fix CVE-2024-28149
  2/contrib/openshift/base-plugins.txt
  2/contrib/openshift/bundle-plugins.txt
Labels: lgtm, approved, jira/valid-reference

#1779 update OWNERS
  OWNERS
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
