Repository openshift/jenkins, pull requests merged in 2024-08, with the labels that each got.

#1758 Bump Jenkins and Java version
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  2/contrib/openshift/jenkins-version.txt
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, ok-to-test, px-approved, docs-approved, qe-approved

#1831 Revert "[release-4.15] Bump Jenkins and Java version"
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  2/contrib/openshift/jenkins-version.txt
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed

#1832 Revert "Bump Jenkins and Java version"
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  2/contrib/openshift/jenkins-version.txt
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved

#1834 OCPTOOLS-468: mitigate CVE-2024-43044
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-reference

#1833 OCPTOOLS-470: mitigate CVE-2024-43044
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-reference

#1835 OCPTOOLS-469: mitigate CVE-2024-43044
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-reference

#1836 OCPTOOLS-467: mitigate CVE-2024-43044
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-reference

#1837 Update Java to JDK 21
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  2/contrib/openshift/jenkins-version.txt
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1838 Update Java to JDK 21
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed

#1839 Update Java to JDK 21
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed

#1840 Update Java to JDK 21
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
Labels: approved
