Repository openshift/jenkins, pull requests merged in 2024-10, with the labels that each got.

#1853 JKNS-529: Remove java 11 usage
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  2/contrib/s2i/run
  BASIC_USAGE.md
  CONTRIBUTING.md
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, jira/valid-reference

#1769 JKNS-384: Update Jenkins base images to RHEL9
  .ci-operator.yaml
  2/Dockerfile.rhel9
  2/go-init/Dockerfile
  slave-base/Dockerfile.rhel9
  slave-base/go-init/Dockerfile
Labels: lgtm, approved, jira/valid-reference

#1865 JKNS-500: Remove java 11 usage
  2/Dockerfile.localdev
  2/Dockerfile.rhel8
  2/contrib/s2i/run
  BASIC_USAGE.md
  CONTRIBUTING.md
  openshift/templates/jenkins-ephemeral-monitored.json
  openshift/templates/jenkins-ephemeral.json
  openshift/templates/jenkins-persistent-monitored.json
  openshift/templates/jenkins-persistent.json
  slave-base/Dockerfile.localdev
  slave-base/Dockerfile.rhel8
  slave-base/contrib/bin/run-jnlp-client
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-reference

#1866 OCPTOOLS-483: Bump to jenkins version 2.462.3
  2/contrib/openshift/jenkins-version.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-reference

#1874 JKNS-463: Containerfile for Konflux
  2/.konflux/Containerfile
  2/contrib/jenkins/install-jenkins-core-plugins.sh
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-reference
